name: Bindings Regeneration

on:
  schedule:
    - cron: '0 0 * * Fri'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for gr2m/create-or-update-pull-request-action to push local changes
      pull-requests: write  # for gr2m/create-or-update-pull-request-action to create a PR
    runs-on: windows-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87
      with:
        dotnet-version: 3.1.302
    - name: Run a full run of BuildTools
      run: dotnet run --project "src/Core/BuildTools/BuildTools.csproj" -- build/binder_scripts/fullrun.json
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    - name: Create or Update Pull Request
      uses: gr2m/create-or-update-pull-request-action@466b1b84c3291c6c69bc56377a6de54a1f4a297c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Binding and specification updates
        body: Regenerates the bindings and the cached specifications with the latest upstream specifications.
        branch: patch/spec-updates
        author: "Ultz Limited <31213871+UltzLtd@users.noreply.github.com>"
        commit-message: Latest bindings as of ${{ steps.date.outputs.date }}
