name: Website Build
on:
  push:
    branches:
      - 'main'
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  Build:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      with:
        submodules: 'true'
        token: ${{ secrets.PUSHABLE_GITHUB_TOKEN }}
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87
      with:
        dotnet-version: 5.0.401
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87
      with:
        dotnet-version: 6.0.201
    - name: Checkout Website Branch
      run: |
        git fetch --all
        git checkout ci/github-pages
        git config --local user.email "9011267+dotnet-bot@users.noreply.github.com"
        git config --local user.name "The Silk.NET Automaton"
        git merge --allow-unrelated-histories -X theirs main
    - name: Run Statiq
      run: dotnet run -c Release --project src/Website/Silk.NET.Statiq/Silk.NET.Statiq.csproj -- -l debug --nocache
    - name: Push to Website Branch
      run: |
        git add -f docs/
        git commit -am "Push latest built GitHub Pages site"
        git push
